# Docker Compose override file for local development
# This file is automatically merged with docker-compose.yml when running docker-compose commands

version: '3.8'

services:
  backend:
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:delegated
      - ./prisma:/app/prisma:delegated
      # Prevent overwriting node_modules and dist
      - /app/node_modules
      - /app/dist
    environment:
      # Development-specific environment variables
      NODE_ENV: development
      LOG_LEVEL: debug

