name: Docker Build and Test

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: false
          tags: vevent-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start services
        run: |
          docker-compose up -d postgres redis
          sleep 10

      - name: Run Prisma migrations
        run: |
          docker-compose run --rm backend npx prisma migrate deploy

      - name: Health check
        run: |
          docker-compose up -d backend
          sleep 10
          curl --fail http://localhost:3000/health || exit 1

      - name: Show logs on failure
        if: failure()
        run: docker-compose logs

      - name: Clean up
        if: always()
        run: docker-compose down -v

